language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
dist: trusty
notifications:
  email: false
script:
  - py.test tests/travis.py
  - py.test tests/interpreter_tests.py
  - py.test tests/bot_tests.py
